"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[3529],{3905:(e,r,n)=>{n.r(r),n.d(r,{MDXContext:()=>c,MDXProvider:()=>m,mdx:()=>y,useMDXComponents:()=>u,withMDXComponents:()=>p});var t=n(67294);function o(e,r,n){return r in e?Object.defineProperty(e,r,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[r]=n,e}function a(){return a=Object.assign||function(e){for(var r=1;r<arguments.length;r++){var n=arguments[r];for(var t in n)Object.prototype.hasOwnProperty.call(n,t)&&(e[t]=n[t])}return e},a.apply(this,arguments)}function i(e,r){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var t=Object.getOwnPropertySymbols(e);r&&(t=t.filter((function(r){return Object.getOwnPropertyDescriptor(e,r).enumerable}))),n.push.apply(n,t)}return n}function s(e){for(var r=1;r<arguments.length;r++){var n=null!=arguments[r]?arguments[r]:{};r%2?i(Object(n),!0).forEach((function(r){o(e,r,n[r])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):i(Object(n)).forEach((function(r){Object.defineProperty(e,r,Object.getOwnPropertyDescriptor(n,r))}))}return e}function l(e,r){if(null==e)return{};var n,t,o=function(e,r){if(null==e)return{};var n,t,o={},a=Object.keys(e);for(t=0;t<a.length;t++)n=a[t],r.indexOf(n)>=0||(o[n]=e[n]);return o}(e,r);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);for(t=0;t<a.length;t++)n=a[t],r.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var c=t.createContext({}),p=function(e){return function(r){var n=u(r.components);return t.createElement(e,a({},r,{components:n}))}},u=function(e){var r=t.useContext(c),n=r;return e&&(n="function"==typeof e?e(r):s(s({},r),e)),n},m=function(e){var r=u(e.components);return t.createElement(c.Provider,{value:r},e.children)},d={inlineCode:"code",wrapper:function(e){var r=e.children;return t.createElement(t.Fragment,{},r)}},h=t.forwardRef((function(e,r){var n=e.components,o=e.mdxType,a=e.originalType,i=e.parentName,c=l(e,["components","mdxType","originalType","parentName"]),p=u(n),m=o,h=p["".concat(i,".").concat(m)]||p[m]||d[m]||a;return n?t.createElement(h,s(s({ref:r},c),{},{components:n})):t.createElement(h,s({ref:r},c))}));function y(e,r){var n=arguments,o=r&&r.mdxType;if("string"==typeof e||o){var a=n.length,i=new Array(a);i[0]=h;var s={};for(var l in r)hasOwnProperty.call(r,l)&&(s[l]=r[l]);s.originalType=e,s.mdxType="string"==typeof e?e:o,i[1]=s;for(var c=2;c<a;c++)i[c]=n[c];return t.createElement.apply(null,i)}return t.createElement.apply(null,n)}h.displayName="MDXCreateElement"},53191:(e,r,n)=>{n.r(r),n.d(r,{frontMatter:()=>s,contentTitle:()=>l,metadata:()=>c,toc:()=>p,default:()=>m});var t=n(87462),o=n(63366),a=(n(67294),n(3905)),i=["components"],s={id:"use-error-boundary",title:"useErrorBoundary"},l=void 0,c={unversionedId:"mainconcepts/use-error-boundary",id:"mainconcepts/use-error-boundary",isDocsHomePage:!1,title:"useErrorBoundary",description:"useErrorBoundary allows components to catch and handle errors higher up in the tree and provide appropriate fallback, logging or retry mechanisms.",source:"@site/../docs/mainconcepts/use-error-boundary.mdx",sourceDirName:"mainconcepts",slug:"/mainconcepts/use-error-boundary",permalink:"/docs/mainconcepts/use-error-boundary",editUrl:"https://github.com/facebook/litho/edit/master/website/../docs/mainconcepts/use-error-boundary.mdx",tags:[],version:"current",frontMatter:{id:"use-error-boundary",title:"useErrorBoundary"},sidebar:"mainSidebar",previous:{title:"useRef",permalink:"/docs/mainconcepts/use-ref"},next:{title:"Layout System with Flexbox",permalink:"/docs/mainconcepts/flexbox-yoga"}},p=[{value:"Example: Showing an Error State in UI",id:"example-showing-an-error-state-in-ui",children:[{value:"Re-raising Errors",id:"re-raising-errors",children:[],level:3}],level:2},{value:"Why not Try/Catch?",id:"why-not-trycatch",children:[],level:2}],u={toc:p};function m(e){var r=e.components,n=(0,o.Z)(e,i);return(0,a.mdx)("wrapper",(0,t.Z)({},u,n,{components:r,mdxType:"MDXLayout"}),(0,a.mdx)("p",null,(0,a.mdx)("inlineCode",{parentName:"p"},"useErrorBoundary")," allows components to catch and handle errors higher up in the tree and provide appropriate fallback, logging or retry mechanisms."),(0,a.mdx)("p",null,"A component becomes an error boundary when it declares a ",(0,a.mdx)("inlineCode",{parentName:"p"},"useErrorBoundary")," hook. The lambda passed to ",(0,a.mdx)("inlineCode",{parentName:"p"},"useErrorBoundary")," will receive any exceptions that are raised in rendering or dispatching events of components sitting underneath the error boundary in the tree."),(0,a.mdx)("p",null,(0,a.mdx)("inlineCode",{parentName:"p"},"useErrorBoundary")," can be used in combination with ",(0,a.mdx)("a",{parentName:"p",href:"/docs/mainconcepts/use-state"},(0,a.mdx)("inlineCode",{parentName:"a"},"useState")),", to update the state with the exception that was caught. This will then trigger a render pass with the new state value in order to replace the crashing component with an error message, or not display it at all."),(0,a.mdx)("h2",{id:"example-showing-an-error-state-in-ui"},"Example: Showing an Error State in UI"),(0,a.mdx)("p",null,"The code sample below shows how a component can gracefully handle an error in one of its child components and render an error state instead of crashing the app:"),(0,a.mdx)("pre",null,(0,a.mdx)("code",{parentName:"pre",className:"language-kotlin",metastring:"file=sample/src/main/java/com/facebook/samples/litho/kotlin/errors/KErrorBoundary.kt start=start_example end=end_example",file:"sample/src/main/java/com/facebook/samples/litho/kotlin/errors/KErrorBoundary.kt",start:"start_example",end:"end_example"},'class KErrorBoundary(private val childComponent: Component) : KComponent() {\n\n  override fun ComponentScope.render(): Component? {\n    val errorState = useState<Exception?> { null }\n    useErrorBoundary { exception: Exception -> errorState.update(exception) }\n\n    errorState.value?.let {\n      return Column(style = Style.margin(all = 16.dp)) {\n        child(KDebugComponent(message = "KComponent\'s Error Boundary", throwable = it))\n      }\n    }\n\n    return childComponent\n  }\n}\n')),(0,a.mdx)("h3",{id:"re-raising-errors"},"Re-raising Errors"),(0,a.mdx)("p",null,"An error boundary may choose to only handle certain classes of errors. You can re-raise an exception from within the ",(0,a.mdx)("inlineCode",{parentName:"p"},"useErrorBoundary")," hook so that it propagates up the component tree until it is either caught by another error boundary or hits the root and causes a crash. This is done by calling ",(0,a.mdx)("a",{parentName:"p",href:"pathname:///javadoc/com/facebook/litho/ComponentUtils.html#raise-com.facebook.litho.ComponentContext-java.lang.Exception-"},(0,a.mdx)("inlineCode",{parentName:"a"},"ComponentUtils.raise"))," with your context and the exception."),(0,a.mdx)("h2",{id:"why-not-trycatch"},"Why not Try/Catch?"),(0,a.mdx)("p",null,"You may wonder why all this additional infrastructure would be necessary when you could just use try/catch. It turns out that there is no easily accessible place to wrap your Component code like this."),(0,a.mdx)("p",null,"The following example shows how ",(0,a.mdx)("strong",{parentName:"p"},"not")," to do it:"),(0,a.mdx)("pre",null,(0,a.mdx)("code",{parentName:"pre",className:"language-kotlin",metastring:"file=sample/src/main/java/com/facebook/samples/litho/kotlin/errors/KIncorrectErrorHandlingComponent.kt start=start_example end=end_example",file:"sample/src/main/java/com/facebook/samples/litho/kotlin/errors/KIncorrectErrorHandlingComponent.kt",start:"start_example",end:"end_example"},'class KIncorrectErrorHandlingComponent : KComponent() {\n\n  override fun ComponentScope.render(): Component {\n    // This implementation won\'t work - you need to implement error boundary with useErrorBoundary\n    // hook instead.\n    return try {\n      // PossiblyCrashingSubTitleComponent can crash\n      PossiblyCrashingSubTitleComponent.create(context).subtitle("example").build()\n    } catch (e: Exception) {\n      // error handling code\n      KDebugComponent(message = "Error Component", throwable = e)\n    }\n  }\n}\n')),(0,a.mdx)("p",null,"Assuming that PossiblyCrashingSubTitleComponent throws an exception in onCreateLayout this would not be caught by this block. The reason for this is that you are just returning a declaration of your layout here and don't actually execute any code. This is the responsibility of the Litho framework, hence the need to provide higher-level infrastructure to give you access to those errors."))}m.isMDXComponent=!0}}]);